import { type ReactNode, useEffect, useState } from "react";
import { useRoute } from "wouter";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { api, money } from "@/lib/api";

function Shell({ title, children }: { title: string; children: ReactNode }) { return <DashboardLayout><div className="space-y-6"><h1 className="text-3xl font-semibold">{title}</h1>{children}</div></DashboardLayout>; }
function useList<T>(path:string){const [items,setItems]=useState<T[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);const load=async()=>{try{setItems(await api<T[]>(path))}catch(e){setError((e as Error).message)}finally{setLoading(false)}};useEffect(()=>{void load()},[path]);return{items,error,loading,load};}

export function BudgetsPage(){const b=useList<any>("/budgets"),c=useList<any>("/categories");const[amount,setAmount]=useState(""),[period,setPeriod]=useState(new Date().toISOString().slice(0,7)),[categoryId,setCategory]=useState("");useEffect(()=>setCategory(x=>x||c.items[0]?.id||""),[c.items]);return <Shell title="Orçamentos"><div className="flex gap-2"><select value={categoryId} onChange={e=>setCategory(e.target.value)}>{c.items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/><Input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Valor"/><Button disabled={!categoryId||!amount} onClick={async()=>{await api("/budgets",{method:"POST",body:JSON.stringify({categoryId,period,amount})});setAmount("");b.load()}}>Novo orçamento</Button></div>{b.error&&<p className="text-destructive">{b.error}</p>}{b.loading?<p>Carregando...</p>:b.items.length?<div className="grid md:grid-cols-3 gap-3">{b.items.map(x=><Card key={x.id}><CardContent className="p-4"><p>{c.items.find(y=>y.id===x.categoryId)?.name||"Categoria"}</p><b>{money(x.amount)}</b><small className="block">{x.period}</small><Button variant="destructive" size="sm" className="mt-2" onClick={async()=>{await api(`/budgets/${x.id}`,{method:"DELETE"});b.load()}}>Excluir</Button></CardContent></Card>)}</div>:<p className="text-muted-foreground">Nenhum orçamento cadastrado.</p>}</Shell>}
export function CategoryHistoryPage(){const [items,setItems]=useState<Array<{label:string;amount:number}>>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{api<{items:Array<{label:string;amount:number}>}>("/reports/category-trends").then(x=>setItems(x.items)).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);return <Shell title="Histórico de Categorias">{error&&<p className="text-destructive">{error}</p>}{loading?<p>Carregando...</p>:items.length?<Card><CardContent className="p-5">{items.map(x=><div className="flex justify-between border-b py-3" key={x.label}><span>{x.label}</span><b>{money(x.amount)}</b></div>)}</CardContent></Card>:<p className="text-muted-foreground">Ainda não há lançamentos para o histórico.</p>}</Shell>}
export function PayersPage(){const r=useList<any>("/payers"),[name,setName]=useState("");return <Shell title="Pagadores"><div className="flex gap-2"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do pagador"/><Button disabled={!name} onClick={async()=>{await api("/payers",{method:"POST",body:JSON.stringify({name})});setName("");r.load()}}>Novo pagador</Button></div>{r.error&&<p className="text-destructive">{r.error}</p>}{r.loading?<p>Carregando...</p>:r.items.length?r.items.map(x=><Card key={x.id} className="mb-2"><CardContent className="p-4 flex justify-between"><span>{x.name}<small className="block">{x.email||"Sem e-mail"}</small></span><Button size="sm" variant="destructive" onClick={async()=>{await api(`/payers/${x.id}`,{method:"DELETE"});r.load()}}>Excluir</Button></CardContent></Card>):<p className="text-muted-foreground">Nenhum pagador cadastrado.</p>}</Shell>}
export function PayerDetailsPage(){const[,p]=useRoute("/payers/:payerId");const r=useList<any>("/payers");const item=r.items.find(x=>x.id===p?.payerId);return <Shell title="Detalhes do Pagador">{r.loading?<p>Carregando...</p>:item?<Card><CardContent className="p-5"><b>{item.name}</b><p>{item.email||"Sem e-mail"}</p><p className="text-muted-foreground">{item.note||"Sem observações."}</p></CardContent></Card>:<p className="text-muted-foreground">Pagador não encontrado.</p>}</Shell>}
function SimplePage({title,path,field="title"}:{title:string;path:string;field?:string}){const r=useList<any>(path),[value,setValue]=useState("");return <Shell title={title}><div className="flex gap-2"><Input value={value} onChange={e=>setValue(e.target.value)} placeholder={`Novo ${title.toLowerCase()}`}/><Button disabled={!value} onClick={async()=>{await api(path,{method:"POST",body:JSON.stringify(field==="originalText"?{originalText:value}:{[field]:value,data:field==="data"?{texto:value}:undefined})});setValue("");r.load()}}>Adicionar</Button></div>{r.error&&<p className="text-destructive">{r.error}</p>}{r.loading?<p>Carregando...</p>:r.items.length?r.items.map(x=><Card className="mb-2" key={x.id}><CardContent className="p-4 flex justify-between"><span>{x.title||x.originalText||x.modelId||x.fileName}</span><Button size="sm" variant="destructive" onClick={async()=>{await api(`${path}/${x.id}`,{method:"DELETE"});r.load()}}>Excluir</Button></CardContent></Card>):<p className="text-muted-foreground">Nenhum registro encontrado.</p>}</Shell>}
export const NotesPage=()=> <SimplePage title="Anotações" path="/notes"/>;
export const InsightsPage=()=> <SimplePage title="Insights Salvos" path="/insights" field="data"/>;
export function InboxPage(){const r=useList<any>("/inbox"),[value,setValue]=useState("");return <Shell title="Caixa de Entrada"><div className="flex gap-2"><Input value={value} onChange={e=>setValue(e.target.value)} placeholder="Novo item"/><Button disabled={!value} onClick={async()=>{await api("/inbox",{method:"POST",body:JSON.stringify({originalText:value})});setValue("");r.load()}}>Adicionar</Button></div>{r.error&&<p className="text-destructive">{r.error}</p>}{r.loading?<p>Carregando...</p>:r.items.length?r.items.map(x=><Card className="mb-2" key={x.id}><CardContent className="p-4 flex justify-between"><span>{x.originalText}<small className="block">{x.status}</small></span><div className="flex gap-2">{x.status!=="read"&&<Button size="sm" variant="outline" onClick={async()=>{await api(`/inbox/${x.id}`,{method:"PATCH",body:JSON.stringify({...x,status:"read"})});r.load()}}>Marcar como lido</Button>}<Button size="sm" variant="destructive" onClick={async()=>{await api(`/inbox/${x.id}`,{method:"DELETE"});r.load()}}>Excluir</Button></div></CardContent></Card>):<p className="text-muted-foreground">Nenhum registro encontrado.</p>}</Shell>}
export function CalendarPage(){const r=useList<any>("/calendar");return <Shell title="Calendário">{r.loading?<p>Carregando...</p>:r.items.length?r.items.map(x=><Card className="mb-2" key={x.id}><CardContent className="p-3">{x.purchaseDate} — {x.name} — {money(x.amount)}</CardContent></Card>):<p className="text-muted-foreground">Nenhuma data com lançamentos.</p>}</Shell>}
export function AttachmentsPage(){const r=useList<any>("/attachments"),[name,setName]=useState(""),[content,setContent]=useState("");return <Shell title="Anexos"><div className="flex gap-2"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do arquivo"/><Input value={content} onChange={e=>setContent(e.target.value)} placeholder="Conteúdo de texto"/><Button disabled={!name||!content} onClick={async()=>{await api("/attachments",{method:"POST",body:JSON.stringify({fileName:name,content})});setName("");setContent("");r.load()}}>Enviar</Button></div>{r.items.map(x=><Card className="my-2" key={x.id}><CardContent className="p-3 flex justify-between"><a className="underline" href={`/api/attachments/${x.id}/download`}>{x.fileName}</a><Button size="sm" variant="destructive" onClick={async()=>{await api(`/attachments/${x.id}`,{method:"DELETE"});r.load()}}>Excluir</Button></CardContent></Card>)}</Shell>}
export function ReportsPage(){const[,p]=useRoute("/reports/:reportId");const id=p?.reportId||"category-trends";const [items,setItems]=useState<Array<{label:string;amount:number}>>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{setLoading(true);api<{items:Array<{label:string;amount:number}>}>(`/reports/${id}`).then(x=>setItems(x.items)).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[id]);return <Shell title="Relatórios"><p className="text-muted-foreground">Agregado: {id}</p>{error&&<p className="text-destructive">{error}</p>}{loading?<p>Carregando...</p>:items.length?items.map(x=><Card className="mb-2" key={x.label}><CardContent className="p-3 flex justify-between"><span>{x.label}</span><b>{money(x.amount)}</b></CardContent></Card>):<p className="text-muted-foreground">Nenhum dado para este relatório.</p>}</Shell>}